//Add watch window variables
expRemoveAll
expAdd("fail",getNatural())
expAdd("pass",getNatural())
expAdd ("vector1",getNatural())
expAdd ("vector2",getNatural())
expAdd ("vector3",getNatural())
expAdd ("vector4",getNatural())
expAdd ("max1",getNatural())
expAdd ("index1",getNatural())
expAdd ("max2",getNatural())
expAdd ("index2",getNatural())
expAdd ("max3",getNatural())
expAdd ("index3",getNatural())
expAdd ("max4",getNatural())
expAdd ("min4",getNatural())
